### ISSUE TITLE
Demo site its bugged

### ISSUE THREAD

**Issue by strikermdd** [mazipan/vue2-simplert#1]
I try the demo site but, when clicked, its show all icons at once, with no text and can't click the button. Something its wrong?

**Comment by mazipan** [comment]
Thanks for reporting.
I will check soon.
Or you can create your pull request if you think you can fix that.

**Comment by mazipan** [comment]
has been fixed [here](https://github.com/mazipan/vue2-simplert/commit/b1703254023092e63ba29a566cb72f929afc3675).

thanks.
