### ISSUE TITLE
Disable click on modal FR

### ISSUE THREAD

**Issue by strixy** [mazipan/vue2-simplert#23]
As a feature, it would be nice if we could disable the click on modal event so the user is forced to click on a button to continue. This makes more sense now that the second button is a feature.

**Comment by mazipan** [comment]
What do you mean with "modal event" )
Is it Overlay click to close modal @strixy ?

**Comment by strixy** [comment]
@mazipan Yes. That's the one.

**Comment by mazipan** [comment]
Closed with new version release, check your version to use this feature.

[![version](https://img.shields.io/npm/v/vue2-simplert.svg)](https://www.npmjs.com/package/vue2-simplert)
