### ISSUE TITLE
what is the use radius option?

### ISSUE THREAD

**Issue by lunfel** [mazipan/vue2-simplert#29]
In the documentation it is written that there is a breaking change for useRadius, but nowhere is says what it does. I tried putting it true or false, can't seem to get what is the difference.

**Comment by mazipan** [comment]
It should change the round corner of simplert box and button @lunfel.
Is it not affected ?

**Comment by lunfel** [comment]
Ahh! Didn't even notice when I played around. 

I would writte it like this. It's a suggestion. Feel free to write it in your own words. 
"Setting useRadius to true will make Simplert's massage box and buttons have rounded corners"

**Comment by mazipan** [comment]
So, is it just misunderstanding from documentation ? Or is it bugs in code ?

**Comment by lunfel** [comment]
I need check again when I get back home to see if makes the corner rounded. I think that I just didn't notice since I didn't know what I was looking for. That's for sure that the doc will be more clear though.

**Comment by mazipan** [comment]
Very thanks for your feedback.
I am in holiday too, so can not update in few weeks.
But let me know if it is a bug.
If it's documentation wrong, I will update it.

Thanks 😉

**Comment by lunfel** [comment]
Cool! Will do

**Comment by mazipan** [comment]
Documentation has been updated for this issue.
Check here : https://github.com/mazipan/vue2-simplert/wiki/Methods-And-Props

👍

**Comment by lunfel** [comment]
I made a typo massage - > message

**Comment by lunfel** [comment]
Everything works fine!
