### ISSUE TITLE
custom button class does not work

### ISSUE THREAD

**Issue by SoarLin** [mazipan/vue2-simplert#30]
I try to use "customConfirmBtnClass" to set up confirm button class, e.g. 'btn-warning'
then the confirm btn class is like "simplert__confirm simplert__confirm--radius btn-warning"

Finally the background-color style is re-write by "simplert__confirm"

**Comment by mazipan** [comment]
Yes for now we just added custom class to existing class.
So if you need quick hack you must add !important in your custom class.
But next version (*soon) we think to remove existing class and replace with just custom class.
Thanks for your feedback @SoarLin

**Comment by mazipan** [comment]
Fix with new version 0.3.0, please update version to use this bug fix

**Comment by SoarLin** [comment]
Thank you, I already hack code to add custom style for inline style.
But this is not a good solution, thanks for your update.

**Comment by mazipan** [comment]
:warning:  You will lose your default class when using custom class, so you must style by yourself.
