### ISSUE TITLE
Can I use vue2-simplert with `<script>`?

### ISSUE THREAD

**Issue by HomoEfficio** [mazipan/vue2-simplert#36]
Hi, I found this is great and I really want use this.

But I'm not good at front-end stuff, so I don't use NPM.

I tried it like this, https://jsbin.com/vomifupiku/edit?html,js,console,output 

But it doesn't work.

How can I use the vue2-simplert with simiple `<script>`?

**Comment by mazipan** [comment]
I am very sorry for you.
It's known issue in #33
I try to compile to browser use with `script` but still failed

**Comment by mazipan** [comment]
Congratulation @HomoEfficio now you can use in v.0.5.1

Just use this script url
```
https://unpkg.com/vue2-simplert@0.5.1/dist/simplert.bundle.js
```

**Comment by HomoEfficio** [comment]
Wow, it works!!

Thank you so much for the quickest ever fix!!

**Comment by mazipan** [comment]
Don't forget to star this repo 😋

**Comment by HomoEfficio** [comment]
Sure!
