### ISSUE TITLE
请问如何当做插件全局注册，每次需要弹窗了就引用用下插件吧，这个很不友好

### ISSUE THREAD

**Issue by victoryboss** [mazipan/vue2-simplert#37]
假如我有好多个页面，岂不是有好多个modal~,

**Comment by mazipan** [comment]
Can you type in English please @victoryboss ?

**Comment by victoryboss** [comment]
I'm sorry.
Thank you for developing this component. It works well with my app. 
But now I have to  use it everywhere，that makes my pages so many modals. It is terrible.
How can I make it work like a global vue-plugin (like NProgress etc.)

**Comment by mazipan** [comment]
Thanks for using this component.
For now, I just create this as a component.
Yes, maybe in future I will provide this as Vue Plugin too.
But it takes time to convert as Plugin, I hope it can be done ASAP.

FYI, Pull-Request are welcome :+1:

**Comment by victoryboss** [comment]
ok~:+1:
