### ISSUE TITLE
Cover entire SPA with Simplert modal

### ISSUE THREAD

**Issue by maryheng** [mazipan/vue2-simplert#38]
Hi all,

<img width="1680" alt="screen shot 2017-08-05 at 6 41 08 pm" src="https://user-images.githubusercontent.com/13627091/28994943-e542498c-7a0d-11e7-9126-79e809fef9c8.png">

Currently, I'm doing a Single Page Application (SPA) project, and am using Simplert. The navigation bar, sidebar and the contents are all different components. 

I'm currently invoking the Simplert from the content component. So, is there a way to cover the entire browser page (including the sidebar and navigation bar) with the Simplert modal?

**Comment by mazipan** [comment]
This is not `vue2-simplert` bugs.
But your code to creating Sidebar and Header that have `z-index` too high.
If you see [here](https://github.com/mazipan/vue2-simplert/blob/master/src/simplert.css), class `.simplert` have rule `z-index: 999`.
So you need to set `z-index` of your Sidebar and Header below that value.

Hope this explanation can help you @maryheng.
