### ISSUE TITLE
ERROR can't load Simplert.vue

### ISSUE THREAD

**Issue by canonigi** [mazipan/vue2-simplert#43]
HI,
tried to install your wonderful package but error occurs as follow
```
ERROR in ./node_modules/vue2-simplert/src/Simplert.vue
    Module parse failed: [...]\node_modules\vue2-simplert\src\Simplert.vue Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | <template>
    |   <div class="simplert" role="modal" :class="classSimplert" @click="closeOverlay">
    |     <div class="simplert__content" :class="classContent">
     @ ./node_modules/vue2-simplert/src/main-dist.js 1:0-37
     @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./_src/views/fields/Index.vue
     @ ./_src/views/fields/Index.vue
     @ ./_src/router/routes.js
     @ ./_src/router/index.js
     @ ./_src/boot-app.js
```
package.json
        "vue2-simplert": "^0.5.5"

Tnx.

**Comment by mazipan** [comment]
I can't reproduce this issue, this is maybe your webpack setup

**Comment by mazipan** [comment]
I use this webpack config 
```javascript
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

... webpack

extensions: ['.js', '.vue', '.json'],
modules: [
      resolve('src'),
      resolve('node_modules')
 ],
```

**Comment by canonigi** [comment]
Ok, this is my webpack
[webpack.config.txt](https://github.com/mazipan/vue2-simplert/files/1370782/webpack.config.txt)

**Comment by mazipan** [comment]
Do you have try Plugin version ?
here : https://github.com/mazipan/vue2-simplert-plugin

I recommend using this version for complex project.

**Comment by mazipan** [comment]
All functionality was same, but with no more duplication initialization.

**Comment by canonigi** [comment]
Ok. I'll try this I'll keep it up to date, 
Tnx.

**Comment by canonigi** [comment]
Fine! Plugin works correctly!
Thank you for your support. 
Best regards, James

**Comment by mazipan** [comment]
May you want to give your :star in this project https://github.com/mazipan/vue2-simplert-plugin

Thanks

**Comment by mazipan** [comment]
Closed here : https://github.com/mazipan/vue2-simplert/commit/126ac44a854e658a2b08ea5330fb81d5f4771aa8
with version 0.5.7
