### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by keyurptl** [mazipan/vue2-simplert#44]
Hey Thanks For such great plugin.
But when I am trying to use this getting below error,
https://www.screencast.com/t/6NE7QkXUu

Can you please help me on this.

[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Simplert>
       <Root>

**Comment by mazipan** [comment]
Sorry for this issue, can you check my new version implementation of this Vue2-Simplert ?

https://github.com/mazipan/vue2-simplert-plugin

I will check in monday ya.

**Comment by mazipan** [comment]
Related with #43

**Comment by keyurptl** [comment]
Thanks for replay so you mean I need install new version insisted of that old. this is different version.

**Comment by mazipan** [comment]
Install another plugin, is it more easy to use.
Just click that link and follow instructions in readme.md

**Comment by keyurptl** [comment]
okay Thanks let me try that new one. Thanks for such great support.

**Comment by mazipan** [comment]
Yes, this is weekend. So, I don't code.
I just wanna life in weekend 😅
Let me know if you have problem ya.

This is link for new plugin 
https://github.com/mazipan/vue2-simplert-plugin

**Comment by keyurptl** [comment]
Thanks Man it works. And Enjoy your weekend. Really Thanks you so much for great plugin,  
Will also check more on Monday.

**Comment by mazipan** [comment]
I recommend for keep using new Plugin instead use this version.
It more reusable and avoid you from reinitialize in each components.
Especially if your project will be complex.

**Comment by keyurptl** [comment]
Okay Sure will not  reinitialize again. Yes project is much complicated.  

I also want some advice if you can help me. 
Actually my project is multi module.  Like Add Users and then add some company with which company user is realted. And There is also other module. So I don't have idea How I  Can Manage Multi Module Project in Vue js and With Laravel If you can help me on this it much appreciated. As Per your knowledge I think you have very good knowledge in Vve Js. 

If possible can you suggest me  how to handle multi module Application in VUe js.

**Comment by mazipan** [comment]
Closed here : https://github.com/mazipan/vue2-simplert/commit/126ac44a854e658a2b08ea5330fb81d5f4771aa8
with version 0.5.7
