### ISSUE TITLE
Close button custom title

### ISSUE THREAD

**Issue by alexTitakoff** [mazipan/vue2-simplert#55]
Hello!

Can I define a custom label on a close button?

**Comment by mazipan** [comment]
For now you can't.
But if worth, maybe we can try to develop it.
I also open for any Pull Request if you want.

**Comment by alexTitakoff** [comment]
ok, i will try   ;)

**Comment by alexTitakoff** [comment]
I find the solution.
In template code exist propeties - {{ customCloseBtnText }}.  
that's what I need.

` let obj = { 
          title: 'Предложения успешно отправлены!',
//          message: 'Мы успешно обработали',
          customCloseBtnText: 'lallaa',
          type: 'success',
}`

**Comment by mazipan** [comment]
Oh, I think you mean custom close `X` button. 😂
